Refactored delete command to require i/ prefix
AY1920S1-CS2103T-W12-2/main pull request #104
Opened 2019-10-11 04:45 UTC by limerencee

Also added proper tests for the new delete command.

2019-10-11 18:05 UTC, lightz96 requested changes
LGTM. Can merge after resolving the coding standards violation.

2019-10-11 18:05 UTC, lightz96 commented on src/main/java/thrift/logic/parser/DeleteCommandParser.java
> +                String.format(Messages.MESSAGE_INVALID_COMMAND_FORMAT, DeleteCommand.MESSAGE_USAGE), pe);
There should be 8 spaces instead.

2019-10-12 03:27 UTC, limerencee commented on src/main/java/thrift/logic/parser/DeleteCommandParser.java
> +                String.format(Messages.MESSAGE_INVALID_COMMAND_FORMAT, DeleteCommand.MESSAGE_USAGE), pe);
Fixed in commit 8a5b378.

2019-10-12 03:34 UTC, lightz96 approved these changes

2019-10-12 03:34 UTC, merged