Implement Cloning multiple copies
AY1920S1-CS2103T-W12-2/main pull request #211
Opened 2019-10-28 13:45 UTC by lye-jw

Add ability to Clone multiple copies of a `Transaction` with command `**clone i/INDEX o/OCCURRENCE**`, where `**OCCURRENCE**` is in the format `**FREQUENCY:NUMBER_OF_OCCURRENCES**`.

- `**FREQUENCY**` refers to how far apart the clones are: `daily`, `weekly`, `monthly`, `yearly`.
- `**NUMBER_OF_OCCURRENCES**` refers to how many times the Transaction is cloned.

Note: Tests for new classes and functionality not added yet!

2019-10-28 16:53 UTC, limerencee requested changes
LGTM after minor clarification!

2019-10-28 16:53 UTC, limerencee commented on src/main/java/thrift/logic/commands/exceptions/CommandException.java
> +import thrift.logic.commands.Command;
Is this import used? :open_mouth:

2019-10-28 17:51 UTC, lye-jw commented on src/main/java/thrift/logic/commands/exceptions/CommandException.java
> +import thrift.logic.commands.Command;
Removed in latest update!

2019-10-29 02:53 UTC, lightz96 commented
Should we limit the number of frequencies to a smaller number?

2019-10-29 02:56 UTC, lye-jw commented
> Should we limit the number of frequencies to a smaller number?

Good idea, what would be a good number? 7 so users can populate a week with `daily`, or 12 so users can populate a year with `monthly`? Or even less?

2019-10-29 02:59 UTC, limerencee commented
> > Should we limit the number of frequencies to a smaller number?
> 
> Good idea, what would be a good number? 7 so users can populate a week with `daily`, or 12 so users can populate a year with `monthly`? Or even less?

12 sounds like a reasonable upper bound. :thinking:

2019-10-29 03:11 UTC, lightz96 commented
> > Should we limit the number of frequencies to a smaller number?
> 
> Good idea, what would be a good number? 7 so users can populate a week with `daily`, or 12 so users can populate a year with `monthly`? Or even less?

Sounds good to me. 7 for `daily`, 12 for `monthly`, probably 5 for `yearly`? We need some reasons in case the reviewer starts to ask for the reason.

2019-10-29 03:20 UTC, lye-jw commented
> > > Should we limit the number of frequencies to a smaller number?
> > 
> > 
> > Good idea, what would be a good number? 7 so users can populate a week with `daily`, or 12 so users can populate a year with `monthly`? Or even less?
> 
> Sounds good to me. 7 for `daily`, 12 for `monthly`, probably 5 for `yearly`? We need some reasons in case the reviewer starts to ask for the reason.

`yearly` maxed at 5 is good. But I think everything else should allow up to 12 so user can have freedom in adding more days and weeks.

2019-10-29 04:48 UTC, lightz96 commented
> > > > Should we limit the number of frequencies to a smaller number?
> > > 
> > > 
> > > Good idea, what would be a good number? 7 so users can populate a week with `daily`, or 12 so users can populate a year with `monthly`? Or even less?
> > 
> > 
> > Sounds good to me. 7 for `daily`, 12 for `monthly`, probably 5 for `yearly`? We need some reasons in case the reviewer starts to ask for the reason.
> 
> `yearly` maxed at 5 is good. But I think everything else should allow up to 12 so user can have freedom in adding more days and weeks.

Ok, sounds good to me.

2019-10-29 05:50 UTC, lightz96 commented
If I execute *clone i/1 o/monthly:5* on 31 October, it adds to 29 February because February does not have 31 days (this also applies to months without 31 days), should we allow this to happen? 🤔

2019-10-29 06:22 UTC, lye-jw commented
> If I execute **clone i/1 o/monthly:5** on 31 October, it adds to 29 February because February does not have 31 days (this also applies to months without 31 days), should we allow this to happen? 🤔

Java's `Calendar#add` correctly handles day overflowing for months. 2020 is a leap year so February 2020 has 29 days. From [Calendar documentation](https://docs.oracle.com/javase/6/docs/api/java/util/Calendar.html):

```
Add rule 1. The value of field f after the call minus the value of field f before the call is delta, modulo any overflow that has occurred in field f. Overflow occurs when a field value exceeds its range and, as a result, the next larger field is incremented or decremented and the field value is adjusted back into its range.

Add rule 2. If a smaller field is expected to be invariant, but it is impossible for it to be equal to its prior value because of changes in its minimum or maximum after field f is changed or other constraints, such as time zone offset changes, then its value is adjusted to be as close as possible to its expected value. A smaller field represents a smaller unit of time. HOUR is a smaller field than DAY_OF_MONTH. No adjustment is made to smaller fields that are not expected to be invariant. The calendar system determines what fields are expected to be invariant.
```

2019-10-29 06:37 UTC, lye-jw commented
> If I execute **clone i/1 o/monthly:5** on 31 October, it adds to 29 February because February does not have 31 days (this also applies to months without 31 days), should we allow this to happen? 🤔

That's an interesting point. We have to think about why the transaction is to be repeated and what happens to it for months that don't have those days.

My opinion is to let them add to the last possible day, since most examples I can think of are transactions that occur at the end of the month regardless of specific day, such as salary payday or monthly bill payment.

What does everyone think? @lightz96 @limerencee @krusagiz @kensonoenqh

2019-10-29 06:39 UTC, lightz96 commented
> > If I execute **clone i/1 o/monthly:5** on 31 October, it adds to 29 February because February does not have 31 days (this also applies to months without 31 days), should we allow this to happen? 🤔
> 
> Java's `Calendar#add` correctly handles day overflowing for months. 2020 is a leap year so February 2020 has 29 days. From [Calendar documentation](https://docs.oracle.com/javase/6/docs/api/java/util/Calendar.html):
> 
> ```
> Add rule 1. The value of field f after the call minus the value of field f before the call is delta, modulo any overflow that has occurred in field f. Overflow occurs when a field value exceeds its range and, as a result, the next larger field is incremented or decremented and the field value is adjusted back into its range.
> 
> Add rule 2. If a smaller field is expected to be invariant, but it is impossible for it to be equal to its prior value because of changes in its minimum or maximum after field f is changed or other constraints, such as time zone offset changes, then its value is adjusted to be as close as possible to its expected value. A smaller field represents a smaller unit of time. HOUR is a smaller field than DAY_OF_MONTH. No adjustment is made to smaller fields that are not expected to be invariant. The calendar system determines what fields are expected to be invariant.
> ```

Should we add the transaction with the date 29 February or skip it?

2019-10-29 06:41 UTC, lye-jw commented
> > > If I execute **clone i/1 o/monthly:5** on 31 October, it adds to 29 February because February does not have 31 days (this also applies to months without 31 days), should we allow this to happen? 🤔
> > 
> > 
> > Java's `Calendar#add` correctly handles day overflowing for months. 2020 is a leap year so February 2020 has 29 days. From [Calendar documentation](https://docs.oracle.com/javase/6/docs/api/java/util/Calendar.html):
> > ```
> > Add rule 1. The value of field f after the call minus the value of field f before the call is delta, modulo any overflow that has occurred in field f. Overflow occurs when a field value exceeds its range and, as a result, the next larger field is incremented or decremented and the field value is adjusted back into its range.
> > 
> > Add rule 2. If a smaller field is expected to be invariant, but it is impossible for it to be equal to its prior value because of changes in its minimum or maximum after field f is changed or other constraints, such as time zone offset changes, then its value is adjusted to be as close as possible to its expected value. A smaller field represents a smaller unit of time. HOUR is a smaller field than DAY_OF_MONTH. No adjustment is made to smaller fields that are not expected to be invariant. The calendar system determines what fields are expected to be invariant.
> > ```
> 
> Should we add the transaction with the date 29 February or skip it?

Sorry I misunderstood your comment at first, see my latest previous reply.

2019-10-29 06:48 UTC, lightz96 commented
> > > > If I execute **clone i/1 o/monthly:5** on 31 October, it adds to 29 February because February does not have 31 days (this also applies to months without 31 days), should we allow this to happen? 🤔
> > > 
> > > 
> > > Java's `Calendar#add` correctly handles day overflowing for months. 2020 is a leap year so February 2020 has 29 days. From [Calendar documentation](https://docs.oracle.com/javase/6/docs/api/java/util/Calendar.html):
> > > ```
> > > Add rule 1. The value of field f after the call minus the value of field f before the call is delta, modulo any overflow that has occurred in field f. Overflow occurs when a field value exceeds its range and, as a result, the next larger field is incremented or decremented and the field value is adjusted back into its range.
> > > 
> > > Add rule 2. If a smaller field is expected to be invariant, but it is impossible for it to be equal to its prior value because of changes in its minimum or maximum after field f is changed or other constraints, such as time zone offset changes, then its value is adjusted to be as close as possible to its expected value. A smaller field represents a smaller unit of time. HOUR is a smaller field than DAY_OF_MONTH. No adjustment is made to smaller fields that are not expected to be invariant. The calendar system determines what fields are expected to be invariant.
> > > ```
> > 
> > 
> > Should we add the transaction with the date 29 February or skip it?
> 
> Sorry I misunderstood your comment at first, see my latest previous reply:
> 
> > That's an interesting point. We have to think about why the transaction is to be repeated and what happens to it for months that don't have those days.
> > My opinion is to let them add to the last possible day, since most examples I can think of are transactions that occur at the end of the month regardless of specific day, such as salary payday or monthly bill payment.
> > What does everyone think? @lightz96 @limerencee @krusagiz @kensonoenqh

Good examples that you have come up with. Therefore, I agreed with the fact it should be added to the end of the month regardless of the specific day.

2019-10-29 06:50 UTC, limerencee approved these changes

2019-10-29 06:54 UTC, merged

2019-10-29 06:58 UTC, krusagiz commented
> > If I execute **clone i/1 o/monthly:5** on 31 October, it adds to 29 February because February does not have 31 days (this also applies to months without 31 days), should we allow this to happen? 🤔
> 
> That's an interesting point. We have to think about why the transaction is to be repeated and what happens to it for months that don't have those days.
> 
> My opinion is to let them add to the last possible day, since most examples I can think of are transactions that occur at the end of the month regardless of specific day, such as salary payday or monthly bill payment.
> 
> What does everyone think? @lightz96 @limerencee @krusagiz @kensonoenqh
The PR has been closed but I agree with @lye-jw that it should add to the last possible day. This way, we can handle a recurrence in every last day of the month, just by putting the biggest possible day or an arbitrarily large number.