Update UG on undo, redo, help, exit commands
AY1920S1-CS2103T-W12-2/main pull request #212
Opened 2019-10-28 16:48 UTC by lightz96

Resolves #198

2019-10-28 18:19 UTC, lye-jw requested changes
LGTM after some quick changes!

2019-10-28 18:19 UTC, lye-jw commented on docs/UserGuide.adoc
> +Suppose you want to delete the second transaction (Bursary) in THRIFT, you remove the third transaction instead!
Would a "but" in between sentences make them flow better? e.g. "Suppose you want to delete the second transaction (Bursary) in THRIFT, **but** you remove the third transaction instead!"

2019-10-28 18:19 UTC, lye-jw commented on docs/UserGuide.adoc
> +THRIFT provides an `undo` command to save your trouble! You can revert to the previous state
"**solve** your trouble" may be more grammatically correct.

2019-10-28 18:19 UTC, lye-jw commented on docs/UserGuide.adoc
> +retrieve back the deleted transaction by performing `undo`.
"retrieve" should be enough instead of "retrieve back".

2019-10-28 18:19 UTC, lye-jw commented on docs/UserGuide.adoc
> +Overuse of `undo` command? No worries, THRIFT provides `redo` command to help you in this situation.
"**Misuse**" could convey the meaning more clearly than "overuse".

2019-10-28 18:28 UTC, lightz96 commented
Merge PR #210 first

2019-10-29 02:47 UTC, lye-jw approved these changes

2019-10-29 06:47 UTC, merged