Modified UserGuide
AY1920S1-CS2103T-W12-2/main pull request #267
Opened 2019-11-05 11:16 UTC by krusagiz

Modified UserGuide.

Resolves #251

2019-11-05 14:02 UTC, lightz96 requested changes
LGTM.

Here are some general comments/suggestions:
1. It seems like we have used both title case and sentence case for our title. E.g. Command summary and Quick Start
2. Instead of "FAQ", maybe we should use "Frequently asked questions"

2019-11-05 14:02 UTC, lightz96 commented on docs/UserGuide.adoc
>  * `INDEX` *must be a positive integer* 1, 2, 3, ...
Not sure if it is a good idea to use **bold** because it does not match the meaning of **bold** used in this document. (Applies to the box in `untag`)

2019-11-05 14:02 UTC, lightz96 commented on docs/UserGuide.adoc
> +To execute the `tag` command you have to use the following syntax:
To execute the `tag` command **,** you have to use the following syntax: (Applies to all the commands)

2019-11-05 14:02 UTC, lightz96 commented on docs/UserGuide.adoc
> +* The tag will be coloured according if `TAG_NAME` is a <<TagColours, keyword>>, else it will be in the default colour
Do you mean accordingly?

2019-11-05 14:02 UTC, lightz96 commented on docs/UserGuide.adoc
> +. You type `tag i/2 t/Shopping` into the Command Box and press kbd:[Enter].
It should be **tag i/2 t/Shopping**

2019-11-05 14:02 UTC, lightz96 commented on docs/UserGuide.adoc
> +that the tag has appeared at the entry indicating that it has been successfully tagged.
the tag has appeared at the entry, indicating that it has been successfully tagged.

2019-11-05 14:02 UTC, lightz96 commented on docs/UserGuide.adoc
> +. You want to dissociate the tag _Important_ from "Humble Bundle" (the entry displayed at index 3)
Missing of a sentence to introduce the steps to the user. E.g. "Here’s how you can do that:"

2019-11-05 14:02 UTC, lightz96 commented on docs/UserGuide.adoc
> +. You type `untag i/3 t/Important` into the Command Box and press kbd:[Enter].
It should be **untag i/3 t/Important**

2019-11-05 14:02 UTC, lightz96 commented on docs/UserGuide.adoc
> +since it is not actually very important.
Might want to remove the word `actually`

2019-11-05 14:02 UTC, lightz96 commented on docs/UserGuide.adoc
>  * If no `VALUE` is specified, the value of 1.00 with be used.
... **will** be used

2019-11-05 14:02 UTC, lightz96 commented on docs/UserGuide.adoc
> +****
You might want to indicate that SGD currency is used by default if only one currency is provided by the user.

2019-11-05 14:02 UTC, lightz96 commented on docs/UserGuide.adoc
> +If you want to travel overseas or go for exchange, you will definitely need foreign currencies.
go for **an** exchange

2019-11-05 14:02 UTC, lightz96 commented on docs/UserGuide.adoc
> +. You type `convert v/1000 c/SGD c/USD` into the Command Box and press kbd:[Enter].
It should be **convert v/1000 c/SGD c/USD**

2019-11-05 14:38 UTC, krusagiz commented on docs/UserGuide.adoc
> +To execute the `tag` command you have to use the following syntax:
Changed

2019-11-05 14:38 UTC, krusagiz commented on docs/UserGuide.adoc
> +* The tag will be coloured according if `TAG_NAME` is a <<TagColours, keyword>>, else it will be in the default colour
Fixed.

2019-11-05 14:40 UTC, krusagiz commented on docs/UserGuide.adoc
> +. You type `tag i/2 t/Shopping` into the Command Box and press kbd:[Enter].
Fixed.

2019-11-05 14:40 UTC, krusagiz commented on docs/UserGuide.adoc
>  * `INDEX` *must be a positive integer* 1, 2, 3, ...
Fixed.

2019-11-05 14:42 UTC, krusagiz commented on docs/UserGuide.adoc
> +that the tag has appeared at the entry indicating that it has been successfully tagged.
There's no problem with the comma here. However, I have changed the section about the success message.

2019-11-05 14:52 UTC, krusagiz commented on docs/UserGuide.adoc
> +. You type `untag i/3 t/Important` into the Command Box and press kbd:[Enter].
Fixed.

2019-11-05 14:52 UTC, krusagiz commented on docs/UserGuide.adoc
> +. You want to dissociate the tag _Important_ from "Humble Bundle" (the entry displayed at index 3)
Added them!

2019-11-05 14:53 UTC, krusagiz commented on docs/UserGuide.adoc
> +since it is not actually very important.
Removed.

2019-11-05 14:53 UTC, krusagiz commented on docs/UserGuide.adoc
>  * If no `VALUE` is specified, the value of 1.00 with be used.
Fixed.

2019-11-05 14:54 UTC, krusagiz commented on docs/UserGuide.adoc
> +****
Added.

2019-11-05 14:57 UTC, krusagiz commented on docs/UserGuide.adoc
> +If you want to travel overseas or go for exchange, you will definitely need foreign currencies.
There's a problem here, but it's not what you indicated. 

Changed _go for exchange_ to _go on exchange_.

2019-11-05 14:57 UTC, krusagiz commented on docs/UserGuide.adoc
> +. You type `convert v/1000 c/SGD c/USD` into the Command Box and press kbd:[Enter].
Fixed.

2019-11-06 07:31 UTC, lightz96 approved these changes

2019-11-06 07:31 UTC, merged