Refactor Edit to Update and modify EditCommand syntax
AY1920S1-CS2103T-W12-2/main pull request #94
Opened 2019-10-09 13:43 UTC by lye-jw

Refactors all classes and instances of `edit` to `update`. Modifies syntax of `edit` command to `update` command as listed in UserGuide.

2019-10-09 16:24 UTC, lye-jw commented
Json Storage is also updated correctly.

2019-10-09 16:51 UTC, lye-jw commented
Showing original transaction in status message failed CI due to outdated tests, working on it. In the meantime this PR can be merged if there are no issues.

2019-10-10 09:36 UTC, limerencee requested changes
Looks good! Thanks for your contributions :)
Should be able to merge after the changes are made!

2019-10-10 09:36 UTC, limerencee commented on docs/DeveloperGuide.adoc
> +   Expected: Details of the updated transaction and original value of updated content shown in status message. Corresponding listed transaction reflects changes. Timestamp in the status bar is update
I think we don't display the timestamp in the status bar, perhaps the last sentence could be removed? Same goes for the other points in this section!

2019-10-10 09:36 UTC, limerencee commented on docs/UserGuide.adoc
> +*   `Updated Transaction: [-] Curry Laksa ($10.50) Date: 09/10/2019 Tags: [Food][Lunch]` +
We could omit showing the original transaction details. If there are mistakes the user could either `undo` or just run `update` again?

2019-10-10 09:36 UTC, limerencee commented on src/test/java/thrift/logic/commands/AddExpenseCommandTest.java
> +        public void setTransaction(Transaction target, Transaction updatedTransaction) {
Please update this same method under `AddIncomeCommandTest.java` as well, thank you!

2019-10-10 10:07 UTC, limerencee approved these changes

2019-10-10 10:07 UTC, merged